//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;

namespace WebApiWrapper.Connected_Services.BorrowingProfileProvider {
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="BorrowingProfileParameter", Namespace="http://schemas.datacontract.org/2004/07/Ofa.Moss.ITSService")]
    [Serializable()]
    public partial class BorrowingProfileParameter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [NonSerialized()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [OptionalField()]
        private System.DateTime EndDateField;
        
        [OptionalField()]
        private bool IncludeCPPField;
        
        [OptionalField()]
        private bool IncludeOIICField;
        
        [OptionalField()]
        private System.DateTime StartDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [DataMember()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [DataMember()]
        public bool IncludeCPP {
            get {
                return this.IncludeCPPField;
            }
            set {
                if ((this.IncludeCPPField.Equals(value) != true)) {
                    this.IncludeCPPField = value;
                    this.RaisePropertyChanged("IncludeCPP");
                }
            }
        }
        
        [DataMember()]
        public bool IncludeOIIC {
            get {
                return this.IncludeOIICField;
            }
            set {
                if ((this.IncludeOIICField.Equals(value) != true)) {
                    this.IncludeOIICField = value;
                    this.RaisePropertyChanged("IncludeOIIC");
                }
            }
        }
        
        [DataMember()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="BorrowingProfile", Namespace="http://schemas.datacontract.org/2004/07/Ofa.Moss.ITSService")]
    [Serializable()]
    public partial class BorrowingProfile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [NonSerialized()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [OptionalField()]
        private double ConsolidatedField;
        
        [OptionalField()]
        private int DealsField;
        
        [OptionalField()]
        private double OEFCField;
        
        [OptionalField()]
        private double PercentBorrowedField;
        
        [OptionalField()]
        private string ProfileField;
        
        [OptionalField()]
        private double ProvinceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [DataMember()]
        public double Consolidated {
            get {
                return this.ConsolidatedField;
            }
            set {
                if ((this.ConsolidatedField.Equals(value) != true)) {
                    this.ConsolidatedField = value;
                    this.RaisePropertyChanged("Consolidated");
                }
            }
        }
        
        [DataMember()]
        public int Deals {
            get {
                return this.DealsField;
            }
            set {
                if ((this.DealsField.Equals(value) != true)) {
                    this.DealsField = value;
                    this.RaisePropertyChanged("Deals");
                }
            }
        }
        
        [DataMember()]
        public double OEFC {
            get {
                return this.OEFCField;
            }
            set {
                if ((this.OEFCField.Equals(value) != true)) {
                    this.OEFCField = value;
                    this.RaisePropertyChanged("OEFC");
                }
            }
        }
        
        [DataMember()]
        public double PercentBorrowed {
            get {
                return this.PercentBorrowedField;
            }
            set {
                if ((this.PercentBorrowedField.Equals(value) != true)) {
                    this.PercentBorrowedField = value;
                    this.RaisePropertyChanged("PercentBorrowed");
                }
            }
        }
        
        [DataMember()]
        public string Profile {
            get {
                return this.ProfileField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileField, value) != true)) {
                    this.ProfileField = value;
                    this.RaisePropertyChanged("Profile");
                }
            }
        }
        
        [DataMember()]
        public double Province {
            get {
                return this.ProvinceField;
            }
            set {
                if ((this.ProvinceField.Equals(value) != true)) {
                    this.ProvinceField = value;
                    this.RaisePropertyChanged("Province");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="BorrowingTradeDetailsParameter", Namespace="http://schemas.datacontract.org/2004/07/Ofa.Moss.ITSService")]
    [Serializable()]
    public partial class BorrowingTradeDetailsParameter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [NonSerialized()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [OptionalField()]
        private int DealIDField;
        
        [OptionalField()]
        private bool EnableCppField;
        
        [OptionalField()]
        private bool EnableOiicField;
        
        [OptionalField()]
        private System.DateTime EndDateField;
        
        [OptionalField()]
        private string ProfileNameField;
        
        [OptionalField()]
        private System.DateTime StartDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [DataMember()]
        public int DealID {
            get {
                return this.DealIDField;
            }
            set {
                if ((this.DealIDField.Equals(value) != true)) {
                    this.DealIDField = value;
                    this.RaisePropertyChanged("DealID");
                }
            }
        }
        
        [DataMember()]
        public bool EnableCpp {
            get {
                return this.EnableCppField;
            }
            set {
                if ((this.EnableCppField.Equals(value) != true)) {
                    this.EnableCppField = value;
                    this.RaisePropertyChanged("EnableCpp");
                }
            }
        }
        
        [DataMember()]
        public bool EnableOiic {
            get {
                return this.EnableOiicField;
            }
            set {
                if ((this.EnableOiicField.Equals(value) != true)) {
                    this.EnableOiicField = value;
                    this.RaisePropertyChanged("EnableOiic");
                }
            }
        }
        
        [DataMember()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [DataMember()]
        public string ProfileName {
            get {
                return this.ProfileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileNameField, value) != true)) {
                    this.ProfileNameField = value;
                    this.RaisePropertyChanged("ProfileName");
                }
            }
        }
        
        [DataMember()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="BorrowingTradeDetails", Namespace="http://schemas.datacontract.org/2004/07/Ofa.Moss.ITSService")]
    [Serializable()]
    public partial class BorrowingTradeDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [NonSerialized()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [OptionalField()]
        private double CouponField;
        
        [OptionalField()]
        private string FaceValField;
        
        [OptionalField()]
        private string HedgeCurrencyField;
        
        [OptionalField()]
        private string HedgeInterestField;
        
        [OptionalField()]
        private string HedgeNameField;
        
        [OptionalField()]
        private System.DateTime MDateField;
        
        [OptionalField()]
        private string ProgramNameField;
        
        [OptionalField()]
        private string SNField;
        
        [OptionalField()]
        private System.DateTime TDateField;
        
        [OptionalField()]
        private int TradeNumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [DataMember()]
        public double Coupon {
            get {
                return this.CouponField;
            }
            set {
                if ((this.CouponField.Equals(value) != true)) {
                    this.CouponField = value;
                    this.RaisePropertyChanged("Coupon");
                }
            }
        }
        
        [DataMember()]
        public string FaceVal {
            get {
                return this.FaceValField;
            }
            set {
                if ((object.ReferenceEquals(this.FaceValField, value) != true)) {
                    this.FaceValField = value;
                    this.RaisePropertyChanged("FaceVal");
                }
            }
        }
        
        [DataMember()]
        public string HedgeCurrency {
            get {
                return this.HedgeCurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.HedgeCurrencyField, value) != true)) {
                    this.HedgeCurrencyField = value;
                    this.RaisePropertyChanged("HedgeCurrency");
                }
            }
        }
        
        [DataMember()]
        public string HedgeInterest {
            get {
                return this.HedgeInterestField;
            }
            set {
                if ((object.ReferenceEquals(this.HedgeInterestField, value) != true)) {
                    this.HedgeInterestField = value;
                    this.RaisePropertyChanged("HedgeInterest");
                }
            }
        }
        
        [DataMember()]
        public string HedgeName {
            get {
                return this.HedgeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.HedgeNameField, value) != true)) {
                    this.HedgeNameField = value;
                    this.RaisePropertyChanged("HedgeName");
                }
            }
        }
        
        [DataMember()]
        public System.DateTime MDate {
            get {
                return this.MDateField;
            }
            set {
                if ((this.MDateField.Equals(value) != true)) {
                    this.MDateField = value;
                    this.RaisePropertyChanged("MDate");
                }
            }
        }
        
        [DataMember()]
        public string ProgramName {
            get {
                return this.ProgramNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramNameField, value) != true)) {
                    this.ProgramNameField = value;
                    this.RaisePropertyChanged("ProgramName");
                }
            }
        }
        
        [DataMember()]
        public string SN {
            get {
                return this.SNField;
            }
            set {
                if ((object.ReferenceEquals(this.SNField, value) != true)) {
                    this.SNField = value;
                    this.RaisePropertyChanged("SN");
                }
            }
        }
        
        [DataMember()]
        public System.DateTime TDate {
            get {
                return this.TDateField;
            }
            set {
                if ((this.TDateField.Equals(value) != true)) {
                    this.TDateField = value;
                    this.RaisePropertyChanged("TDate");
                }
            }
        }
        
        [DataMember()]
        public int TradeNum {
            get {
                return this.TradeNumField;
            }
            set {
                if ((this.TradeNumField.Equals(value) != true)) {
                    this.TradeNumField = value;
                    this.RaisePropertyChanged("TradeNum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="BorrowingProfileDealParameter", Namespace="http://schemas.datacontract.org/2004/07/Ofa.Moss.ITSService")]
    [Serializable()]
    public partial class BorrowingProfileDealParameter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [NonSerialized()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [OptionalField()]
        private System.DateTime EndDateField;
        
        [OptionalField()]
        private bool IncludeCPPField;
        
        [OptionalField()]
        private bool IncludeOIICField;
        
        [OptionalField()]
        private string ProfileField;
        
        [OptionalField()]
        private System.DateTime StartDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [DataMember()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [DataMember()]
        public bool IncludeCPP {
            get {
                return this.IncludeCPPField;
            }
            set {
                if ((this.IncludeCPPField.Equals(value) != true)) {
                    this.IncludeCPPField = value;
                    this.RaisePropertyChanged("IncludeCPP");
                }
            }
        }
        
        [DataMember()]
        public bool IncludeOIIC {
            get {
                return this.IncludeOIICField;
            }
            set {
                if ((this.IncludeOIICField.Equals(value) != true)) {
                    this.IncludeOIICField = value;
                    this.RaisePropertyChanged("IncludeOIIC");
                }
            }
        }
        
        [DataMember()]
        public string Profile {
            get {
                return this.ProfileField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileField, value) != true)) {
                    this.ProfileField = value;
                    this.RaisePropertyChanged("Profile");
                }
            }
        }
        
        [DataMember()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="BorrowingProfileDeal", Namespace="http://schemas.datacontract.org/2004/07/Ofa.Moss.ITSService")]
    [Serializable()]
    public partial class BorrowingProfileDeal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [NonSerialized()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [OptionalField()]
        private double ConsolidatedField;
        
        [OptionalField()]
        private int DealIDField;
        
        [OptionalField()]
        private string DescField;
        
        [OptionalField()]
        private string MarketField;
        
        [OptionalField()]
        private double OEFCField;
        
        [OptionalField()]
        private double PercentBorrowedField;
        
        [OptionalField()]
        private string ProfileField;
        
        [OptionalField()]
        private double ProvinceField;
        
        [OptionalField()]
        private System.DateTime TradeDateField;
        
        [OptionalField()]
        private int TradesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [DataMember()]
        public double Consolidated {
            get {
                return this.ConsolidatedField;
            }
            set {
                if ((this.ConsolidatedField.Equals(value) != true)) {
                    this.ConsolidatedField = value;
                    this.RaisePropertyChanged("Consolidated");
                }
            }
        }
        
        [DataMember()]
        public int DealID {
            get {
                return this.DealIDField;
            }
            set {
                if ((this.DealIDField.Equals(value) != true)) {
                    this.DealIDField = value;
                    this.RaisePropertyChanged("DealID");
                }
            }
        }
        
        [DataMember()]
        public string Desc {
            get {
                return this.DescField;
            }
            set {
                if ((object.ReferenceEquals(this.DescField, value) != true)) {
                    this.DescField = value;
                    this.RaisePropertyChanged("Desc");
                }
            }
        }
        
        [DataMember()]
        public string Market {
            get {
                return this.MarketField;
            }
            set {
                if ((object.ReferenceEquals(this.MarketField, value) != true)) {
                    this.MarketField = value;
                    this.RaisePropertyChanged("Market");
                }
            }
        }
        
        [DataMember()]
        public double OEFC {
            get {
                return this.OEFCField;
            }
            set {
                if ((this.OEFCField.Equals(value) != true)) {
                    this.OEFCField = value;
                    this.RaisePropertyChanged("OEFC");
                }
            }
        }
        
        [DataMember()]
        public double PercentBorrowed {
            get {
                return this.PercentBorrowedField;
            }
            set {
                if ((this.PercentBorrowedField.Equals(value) != true)) {
                    this.PercentBorrowedField = value;
                    this.RaisePropertyChanged("PercentBorrowed");
                }
            }
        }
        
        [DataMember()]
        public string Profile {
            get {
                return this.ProfileField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileField, value) != true)) {
                    this.ProfileField = value;
                    this.RaisePropertyChanged("Profile");
                }
            }
        }
        
        [DataMember()]
        public double Province {
            get {
                return this.ProvinceField;
            }
            set {
                if ((this.ProvinceField.Equals(value) != true)) {
                    this.ProvinceField = value;
                    this.RaisePropertyChanged("Province");
                }
            }
        }
        
        [DataMember()]
        public System.DateTime TradeDate {
            get {
                return this.TradeDateField;
            }
            set {
                if ((this.TradeDateField.Equals(value) != true)) {
                    this.TradeDateField = value;
                    this.RaisePropertyChanged("TradeDate");
                }
            }
        }
        
        [DataMember()]
        public int Trades {
            get {
                return this.TradesField;
            }
            set {
                if ((this.TradesField.Equals(value) != true)) {
                    this.TradesField = value;
                    this.RaisePropertyChanged("Trades");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="BorrowingProfileHedges", Namespace="http://schemas.datacontract.org/2004/07/Ofa.Moss.ITSService")]
    [Serializable()]
    public partial class BorrowingProfileHedges : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [NonSerialized()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [OptionalField()]
        private double ConsolidatedField;
        
        [OptionalField()]
        private string DealsField;
        
        [OptionalField()]
        private double OEFCField;
        
        [OptionalField()]
        private double ProvinceField;
        
        [OptionalField()]
        private string SubProgramField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [DataMember()]
        public double Consolidated {
            get {
                return this.ConsolidatedField;
            }
            set {
                if ((this.ConsolidatedField.Equals(value) != true)) {
                    this.ConsolidatedField = value;
                    this.RaisePropertyChanged("Consolidated");
                }
            }
        }
        
        [DataMember()]
        public string Deals {
            get {
                return this.DealsField;
            }
            set {
                if ((object.ReferenceEquals(this.DealsField, value) != true)) {
                    this.DealsField = value;
                    this.RaisePropertyChanged("Deals");
                }
            }
        }
        
        [DataMember()]
        public double OEFC {
            get {
                return this.OEFCField;
            }
            set {
                if ((this.OEFCField.Equals(value) != true)) {
                    this.OEFCField = value;
                    this.RaisePropertyChanged("OEFC");
                }
            }
        }
        
        [DataMember()]
        public double Province {
            get {
                return this.ProvinceField;
            }
            set {
                if ((this.ProvinceField.Equals(value) != true)) {
                    this.ProvinceField = value;
                    this.RaisePropertyChanged("Province");
                }
            }
        }
        
        [DataMember()]
        public string SubProgram {
            get {
                return this.SubProgramField;
            }
            set {
                if ((object.ReferenceEquals(this.SubProgramField, value) != true)) {
                    this.SubProgramField = value;
                    this.RaisePropertyChanged("SubProgram");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BorrowingProfileProvider.IBorrowingProfileProvider")]
    public interface IBorrowingProfileProvider {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorrowingProfileProvider/GetBorrowingProfiles", ReplyAction="http://tempuri.org/IBorrowingProfileProvider/GetBorrowingProfilesResponse")]
        BorrowingProfile[] GetBorrowingProfiles(BorrowingProfileParameter parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorrowingProfileProvider/GetBorrowingProfiles", ReplyAction="http://tempuri.org/IBorrowingProfileProvider/GetBorrowingProfilesResponse")]
        System.Threading.Tasks.Task<BorrowingProfile[]> GetBorrowingProfilesAsync(BorrowingProfileParameter parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorrowingProfileProvider/GetBorrowingTradeDetailsByDeal", ReplyAction="http://tempuri.org/IBorrowingProfileProvider/GetBorrowingTradeDetailsByDealRespon" +
            "se")]
        BorrowingTradeDetails[] GetBorrowingTradeDetailsByDeal(BorrowingTradeDetailsParameter parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorrowingProfileProvider/GetBorrowingTradeDetailsByDeal", ReplyAction="http://tempuri.org/IBorrowingProfileProvider/GetBorrowingTradeDetailsByDealRespon" +
            "se")]
        System.Threading.Tasks.Task<BorrowingTradeDetails[]> GetBorrowingTradeDetailsByDealAsync(BorrowingTradeDetailsParameter parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorrowingProfileProvider/GetBorrowingTradeDetailsByProfile", ReplyAction="http://tempuri.org/IBorrowingProfileProvider/GetBorrowingTradeDetailsByProfileRes" +
            "ponse")]
        BorrowingTradeDetails[] GetBorrowingTradeDetailsByProfile(BorrowingTradeDetailsParameter parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorrowingProfileProvider/GetBorrowingTradeDetailsByProfile", ReplyAction="http://tempuri.org/IBorrowingProfileProvider/GetBorrowingTradeDetailsByProfileRes" +
            "ponse")]
        System.Threading.Tasks.Task<BorrowingTradeDetails[]> GetBorrowingTradeDetailsByProfileAsync(BorrowingTradeDetailsParameter parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorrowingProfileProvider/GetBorrowingDeals", ReplyAction="http://tempuri.org/IBorrowingProfileProvider/GetBorrowingDealsResponse")]
        BorrowingProfileDeal[] GetBorrowingDeals(BorrowingProfileDealParameter parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorrowingProfileProvider/GetBorrowingDeals", ReplyAction="http://tempuri.org/IBorrowingProfileProvider/GetBorrowingDealsResponse")]
        System.Threading.Tasks.Task<BorrowingProfileDeal[]> GetBorrowingDealsAsync(BorrowingProfileDealParameter parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorrowingProfileProvider/GetBorrowingTargets", ReplyAction="http://tempuri.org/IBorrowingProfileProvider/GetBorrowingTargetsResponse")]
        BorrowingProfile GetBorrowingTargets(int fiscalYear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorrowingProfileProvider/GetBorrowingTargets", ReplyAction="http://tempuri.org/IBorrowingProfileProvider/GetBorrowingTargetsResponse")]
        System.Threading.Tasks.Task<BorrowingProfile> GetBorrowingTargetsAsync(int fiscalYear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorrowingProfileProvider/GetBorrowingProfileHedges", ReplyAction="http://tempuri.org/IBorrowingProfileProvider/GetBorrowingProfileHedgesResponse")]
        BorrowingProfileHedges[] GetBorrowingProfileHedges(BorrowingProfileParameter parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorrowingProfileProvider/GetBorrowingProfileHedges", ReplyAction="http://tempuri.org/IBorrowingProfileProvider/GetBorrowingProfileHedgesResponse")]
        System.Threading.Tasks.Task<BorrowingProfileHedges[]> GetBorrowingProfileHedgesAsync(BorrowingProfileParameter parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorrowingProfileProvider/GetBorrowingDealHedges", ReplyAction="http://tempuri.org/IBorrowingProfileProvider/GetBorrowingDealHedgesResponse")]
        BorrowingProfileHedges[] GetBorrowingDealHedges(BorrowingProfileDealParameter parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorrowingProfileProvider/GetBorrowingDealHedges", ReplyAction="http://tempuri.org/IBorrowingProfileProvider/GetBorrowingDealHedgesResponse")]
        System.Threading.Tasks.Task<BorrowingProfileHedges[]> GetBorrowingDealHedgesAsync(BorrowingProfileDealParameter parameters);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBorrowingProfileProviderChannel : IBorrowingProfileProvider, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BorrowingProfileProviderClient : System.ServiceModel.ClientBase<IBorrowingProfileProvider>, IBorrowingProfileProvider {
        
        public BorrowingProfileProviderClient() {
        }
        
        public BorrowingProfileProviderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BorrowingProfileProviderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BorrowingProfileProviderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BorrowingProfileProviderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BorrowingProfile[] GetBorrowingProfiles(BorrowingProfileParameter parameters) {
            return base.Channel.GetBorrowingProfiles(parameters);
        }
        
        public System.Threading.Tasks.Task<BorrowingProfile[]> GetBorrowingProfilesAsync(BorrowingProfileParameter parameters) {
            return base.Channel.GetBorrowingProfilesAsync(parameters);
        }
        
        public BorrowingTradeDetails[] GetBorrowingTradeDetailsByDeal(BorrowingTradeDetailsParameter parameters) {
            return base.Channel.GetBorrowingTradeDetailsByDeal(parameters);
        }
        
        public System.Threading.Tasks.Task<BorrowingTradeDetails[]> GetBorrowingTradeDetailsByDealAsync(BorrowingTradeDetailsParameter parameters) {
            return base.Channel.GetBorrowingTradeDetailsByDealAsync(parameters);
        }
        
        public BorrowingTradeDetails[] GetBorrowingTradeDetailsByProfile(BorrowingTradeDetailsParameter parameters) {
            return base.Channel.GetBorrowingTradeDetailsByProfile(parameters);
        }
        
        public System.Threading.Tasks.Task<BorrowingTradeDetails[]> GetBorrowingTradeDetailsByProfileAsync(BorrowingTradeDetailsParameter parameters) {
            return base.Channel.GetBorrowingTradeDetailsByProfileAsync(parameters);
        }
        
        public BorrowingProfileDeal[] GetBorrowingDeals(BorrowingProfileDealParameter parameters) {
            return base.Channel.GetBorrowingDeals(parameters);
        }
        
        public System.Threading.Tasks.Task<BorrowingProfileDeal[]> GetBorrowingDealsAsync(BorrowingProfileDealParameter parameters) {
            return base.Channel.GetBorrowingDealsAsync(parameters);
        }
        
        public BorrowingProfile GetBorrowingTargets(int fiscalYear) {
            return base.Channel.GetBorrowingTargets(fiscalYear);
        }
        
        public System.Threading.Tasks.Task<BorrowingProfile> GetBorrowingTargetsAsync(int fiscalYear) {
            return base.Channel.GetBorrowingTargetsAsync(fiscalYear);
        }
        
        public BorrowingProfileHedges[] GetBorrowingProfileHedges(BorrowingProfileParameter parameters) {
            return base.Channel.GetBorrowingProfileHedges(parameters);
        }
        
        public System.Threading.Tasks.Task<BorrowingProfileHedges[]> GetBorrowingProfileHedgesAsync(BorrowingProfileParameter parameters) {
            return base.Channel.GetBorrowingProfileHedgesAsync(parameters);
        }
        
        public BorrowingProfileHedges[] GetBorrowingDealHedges(BorrowingProfileDealParameter parameters) {
            return base.Channel.GetBorrowingDealHedges(parameters);
        }
        
        public System.Threading.Tasks.Task<BorrowingProfileHedges[]> GetBorrowingDealHedgesAsync(BorrowingProfileDealParameter parameters) {
            return base.Channel.GetBorrowingDealHedgesAsync(parameters);
        }
    }
}
